---
title: "PamGene_pathway_enrichment"
output: html_document
date: "2025-02-17"
---

```{r}
library(BiocManager)
library(STRINGdb)
library(clusterProfiler)
library(enrichplot)
library(org.Hs.eg.db)
library(ReactomePA)
```

Load in Mart, to add ensembl gene ids

```{r}
mart <- useEnsembl("ensembl", dataset="hsapiens_gene_ensembl", host = 'https://jan2024.archive.ensembl.org')
```
Add ensembl gene ids to Pamkinase

```{r}
Pam_kinase_path = "data/Pam_chip/112_Kinases.xlsx"
Pam_kinase_data <- readxl::read_excel(Pam_kinase_path, sheet = "Sheet2") 

Ensembl_list <- getBM(mart = mart,
                      attribute = c('hgnc_symbol', 'ensembl_gene_id' ,'uniprot_gn_id'),
                      filters = 'uniprot_gn_id',
                      values = Pam_kinase_data$`Kinase Uniprot ID`)

Pam_kinase_data %>%
  left_join(Ensembl_list, by = c("Kinase Uniprot ID"= "uniprot_gn_id"), relationship = "many-to-many") -> Pam_kinase_data_ensembl
```

Add ensembl_gene_ids to pam peptides full list
```{r}
Pam_peptide_final_file_path = "data/Pam_chip/gene_list_pamgene_complete.csv"

Pam_peptide_final_table <- read.csv(Pam_peptide_final_file_path) 

Ensembl_list <- getBM(mart = mart,
           attribute = c('hgnc_symbol', 'ensembl_gene_id'),
           filters = 'hgnc_symbol',
           values = Pam_peptide_final_table$Gene)

Pam_peptide_final_table %>%
  left_join(Ensembl_list, by = c("Gene"= "hgnc_symbol"), relationship = "many-to-many") -> finished_pam_table_full_list

```

String visualizations of PamGene Peptides
```{r}
string_db <- STRINGdb$new(version = "11.5", species = 9606, score_threshold = 400, input_directory="")
PamGene_Peptides_mapped <- string_db$map(data.frame(gene = finished_pam_table_full_list$Gene), "gene", removeUnmappedRows = TRUE )

PamGene_Peptides_plt <- string_db$plot_network(PamGene_Peptides_mapped$STRING_id)



clustersList <- string_db$get_clusters(PamGene_Peptides_mapped$STRING_id[1:600])
par(mfrow=c(2,2))
for(i in seq(1:4)){
   string_db$plot_network(clustersList[[i]])
   }
```
```{r}
enrichmentGO <- string_db$get_enrichment( PamGene_Peptides_mapped$STRING_id, category = "KEGG" )

reactome_res <- enrichPathway(
    gene         = PamGene_Peptides_mapped$ENTREZID,
    organism     = "human",  # Change to "mouse", "rat", etc.
    pvalueCutoff = 0.05
)


enrichplot::dotplot(reactome_res, showCategory=10, title="Reactome Pathway Enrichment")
```




String visualizations of PamGene kinases
```{r}
string_db <- STRINGdb$new(version = "11.5", species = 9606, score_threshold = 400, input_directory="")
PamGene_kinases_mapped <- string_db$map(data.frame(gene = Pam_kinase_data_ensembl$hgnc_symbol), "gene", removeUnmappedRows = TRUE )
string_db$plot_network(PamGene_kinases_mapped$STRING_id)

clustersList <- string_db$get_clusters(PamGene_kinases_mapped$STRING_id[1:600])
par(mfrow=c(2,2))
for(i in seq(1:4)){
   string_db$plot_network(clustersList[[i]])
   }
```

